pseudo-greenlight-poll for WBTC-B
makerdao/community pull request #1080
Opened 2021-01-07 10:42 UTC by ultraschuppi

### Attention (CC)

@LongForWisdom

## Summary of changes

added pseudo-greenlight-poll for adding a ETH-B similar vault-type for WBTC

## Relevant Context

followup of [forum signal](https://forum.makerdao.com/t/signal-request-new-iam-vault-type-for-wbtc-with-lower-lr/5736/3)

2021-01-07 15:33 UTC, LongForWisdom requested changes
Thank you @ultraschuppi! Feel free to make as many of these as you want, I'll clean it up as necessary when I come to merge it and put it up.

2021-01-07 15:33 UTC, LongForWisdom commented on governance/polls/Proposal - add WBTC-B vault type - January 11, 2021.md
> +title: Should we add a new WBTC vault type with lower LR? - January 11, 2021
I would go with something like 'Investigate implementation of a WBTC-B vault-type with a lower LR', also I don't think titles can have '?' due to some weird thing on the portal.

2021-01-07 15:33 UTC, LongForWisdom commented on governance/polls/Proposal - add WBTC-B vault type - January 11, 2021.md
> +title: Should we add a new WBTC vault type with lower LR? - January 11, 2021
I'd update the filename to match this as well.

2021-01-07 15:33 UTC, LongForWisdom commented on governance/polls/Proposal - add WBTC-B vault type - January 11, 2021.md
> +summary: This poll will provide guidance to the Domain Teams for creating a new WBTC based vault type
I think I would take this straight from the greenlight polls: 'Signal your support or opposition to prioritising onboarding a WBTC-B vault-type'

2021-01-07 15:33 UTC, LongForWisdom commented on governance/polls/Proposal - add WBTC-B vault type - January 11, 2021.md
> +# Poll: Should we add a new WBTC vault type with lower LR? - January 11, 2021
Likewise, match title and lose '?'

2021-01-07 15:33 UTC, LongForWisdom commented on governance/polls/Proposal - add WBTC-B vault type - January 11, 2021.md
> +
I'd add a little more detail here as to the similarity of this to greenlight. I'm happy to fill this in later though, so feel free to leave as is.

2021-01-07 15:33 UTC, LongForWisdom commented on governance/polls/Proposal - add WBTC-B vault type - January 11, 2021.md
> +The new vault-type gets added to the collateral prioritisation list for the risk team and other mandated actors to prioritise, evaluate and potentially implement when they feel it is the most valuabl
'A WBTC-B vault-type will be added to the collateral prioritisation list...'

2021-01-08 08:10 UTC, ultraschuppi commented
@LongForWisdom thanks for commenting, tried my very best.

the reason i held of from using "WBTC-B" is that there is a parallel initiative driven by [B.Protocol](https://forum.makerdao.com/t/discussion-wbtc-b-collateral-type-backed-by-b-protocol-with-x10-leverage/5409) that also plans for WBTC-B...

2021-01-08 17:37 UTC, merged