Creating Inclusion Polls for March 8
makerdao/community pull request #1192
Opened 2021-03-05 13:03 UTC by 0xElihu

## Attention (CC)

@prose11

## Summary of changes

Added Inclusion Polls for:
-MIP43
-MIP45
-MIP46

## Relevant Context

To be reviewed by @prose11.

2021-03-05 14:15 UTC, prose11 requested changes
Looking great!

Just need a couple of changes:
-In the first section "# Inclusion Poll for..." The date format is incorrect, currently listed as "March 8, 2021" it should be "Monday, March 8"
- In MIP46 Poll (Parameter Group) there shouldn't be a space between "MIP" and "46" In the title and first section header.

Clean those small things up and we're good to submit!

2021-03-05 16:36 UTC, 0xElihu commented
> Looking great!
> 
> Just need a couple of changes:
> -In the first section "# Inclusion Poll for..." The date format is incorrect, currently listed as "March 8, 2021" it should be "Monday, March 8"
> 
> * In MIP46 Poll (Parameter Group) there shouldn't be a space between "MIP" and "46" In the title and first section header.
> 
> Clean those small things up and we're good to submit!

Incorporated your feedback, thanks!

2021-03-05 16:42 UTC, prose11 approved these changes
Nice work! Looks set to me!

2021-03-05 16:45 UTC, LongForWisdom commented on governance/polls/Inclusion Poll - MIP46- March 8, 2021.md
> +   - Technical
PPG's probably don't belong in the 'Technical' category.

2021-03-05 16:47 UTC, LongForWisdom requested changes

2021-03-05 16:47 UTC, LongForWisdom commented on governance/polls/Inclusion Poll - MIP43- March 8, 2021.md
> +   - Governance
There is a 'MIPs' category that these should be a part of.

2021-03-05 17:27 UTC, prose11 requested changes
We're close I promise lol

2021-03-05 17:27 UTC, prose11 commented on governance/polls/Inclusion Poll - MIP45- March 8, 2021.md
> +   - Technical
Add MIPs Category Tag

2021-03-05 17:27 UTC, prose11 commented on governance/polls/Inclusion Poll - MIP46- March 8, 2021.md
> +   - Technical
Add MIPs tag

2021-03-05 18:22 UTC, LongForWisdom commented on governance/polls/Inclusion Poll - MIP45- March 8, 2021.md
> +   - Technical
Probably lose governance tag as well

2021-03-05 18:22 UTC, LongForWisdom commented on governance/polls/Inclusion Poll - MIP43- March 8, 2021.md
> +   - Governance
lose governance tag

2021-03-07 20:12 UTC, LongForWisdom approved these changes

2021-03-07 20:12 UTC, merged