MIP 9 Community Greenlight Polls - March 15, 2021
makerdao/community pull request #1202
Opened 2021-03-12 17:17 UTC by blimpa

@prose11 , @LongForWisdom :)

2021-03-12 20:02 UTC, prose11 requested changes
Almost there! Name changes and we should be set!

2021-03-12 20:02 UTC, prose11 commented on governance/polls/MIP 9 Community Greenlight Poll - xSUSHI - March 15, 2021.md
> +summary: Signal your support or opposition to prioritising onboarding xSUSHI (Sushibar Token).
Change to "(Sushibar)" in all instances

2021-03-14 12:55 UTC, prose11 approved these changes
Great work!

2021-03-14 19:56 UTC, LongForWisdom approved these changes

2021-03-14 19:56 UTC, merged