Executive Copy - 2021-06-04
makerdao/community pull request #1360
Opened 2021-06-03 16:23 UTC by LongForWisdom

2021-06-03 18:47 UTC, prose11 requested changes
Links are the only real fixes that need to be done, everything else could probably be dismissed as style preference!

2021-06-03 18:47 UTC, prose11 commented on governance/votes/Executive vote - June 4, 2021.md
> +**Liquidations 2.0**
Don't think it's necessarily worth changing, but did notice the vaults are listed in different order here and in the detail section. All there in both sections :+1:

2021-06-03 18:47 UTC, prose11 commented on governance/votes/Executive vote - June 4, 2021.md
> +Due to the recent issue in which the Global Debt Ceiling limited usage of the Maker Protocol for a number of days, the Protocol Engineering Core Unit has proposed increasing the Global Debt Ceiling i
I know we usually have a "from" to "to" format for these increases that wouldn't work with the Global DC

2021-06-03 18:47 UTC, prose11 commented on governance/votes/Executive vote - June 4, 2021.md
> +Due to the recent issue in which the Global Debt Ceiling limited usage of the Maker Protocol for a number of days, the Protocol Engineering Core Unit has proposed increasing the Global Debt Ceiling i
Would it be worth saying something like:

Typically, the Global Debt Ceiling is the sum of all available Debt Ceilings. To alleviate the recent issue, this measure proposes adding a fixed amount of 500M to the sum of the debt ceilings, effectively raising the Global Debt Ceiling by 500M DAI.

2021-06-03 20:20 UTC, LongForWisdom commented on governance/votes/Executive vote - June 4, 2021.md
> +- **642,135 DAI** will be distributed to **Sustainable Ecosystem Scaling (SES-001)** core unit auditors wallet at **0x87AcDD9208f73bFc9207e1f6F0fDE906bcA95cc6** as specified in their active [budget p
Yeah, not sure what to do about this one.

2021-06-04 04:29 UTC, prose11 approved these changes
Looks good to me!

2021-06-04 10:09 UTC, merged