Polls November 15
makerdao/community pull request #1566
Opened 2021-11-12 10:27 UTC by Hipogeo

Hey, @mkrorbrkr ! Here's the polls. Let me know if there's anything that needs to be changed :)

2021-11-12 23:01 UTC, mkrorbrkr requested changes
@Hipogeo just a few minor changes

2021-11-12 23:01 UTC, mkrorbrkr commented on governance/polls/Increase the ilk.hole Parameter for Several Collaterals - November 15, 2021.md
> +   * WSTETH-A: from current 3M to 7M
As before, would spell out "million" and indicate that this is a figure in DAI

See this poll for an example of how you might format this section: https://github.com/makerdao/community/blob/master/governance/polls/Adjusting%20Auction%20Parameters%20for%20ETH-A%2C%20ETH-C%2C%20and%20WBTC-A%20-%20September%2020%2C%202021.md

2021-11-13 23:32 UTC, mkrorbrkr approved these changes
@prose11 @Hipogeo I think this is now good to go :)

2021-11-15 11:39 UTC, prose11 commented on governance/polls/Change of Covenants for P1-DROP (farmlands) - November 15, 2021.md
> +   - Collateral
Adding it in :)

2021-11-15 11:43 UTC, prose11 approved these changes
Looks good to me, I'll swap out "farmlands" for "People's Company Series 1" but given the signal I see why farmlands was put in

2021-11-15 11:43 UTC, merged