Polls 2022 01 06
makerdao/community pull request #1615
Opened 2022-01-06 05:37 UTC by TheExistence

### Attention (CC)

## Summary of changes

_Description of the changes included in this pull request. 
Steps to follow to confirm the feature is completed or the bug/issue is resolved. 
Are there any dependencies? 
Does this code break any existing functionality or introduce any risk?_

## Relevant Context

- Feature: [ticket number](link to project management ticket)
- Relevant Pull Request: # 

## How Has This Been Tested?

## Screenshots (if appropriate):

## Further comments

--- 
## Types of changes

- [ ] Content edit, File upload, content addition
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Technical Documentation Update
- [ ] Other (please describe):

## Does this introduce a breaking change?

_Breaking change is defined as_ **"A fix or feature that would cause existing functionality to change."**

- [ ] Yes
- [ ] No

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added/changed necessary documentation (if appropriate)
- [ ] All new and existing tests passed.

2022-01-06 13:54 UTC, mkrorbrkr requested changes
Looks pretty good! See comments about the TUSD poll

2022-01-06 13:54 UTC, mkrorbrkr commented on governance/polls/MIP9 Community Greenlight Poll - TUSD (TrueUSD) - January 10, 2022.md
> +summary: Signal your support or opposition to prioritising onboarding TUSD (TrueUSD).
Can we make it clear that the application is for a PSM - see the forum thread

2022-01-06 13:54 UTC, mkrorbrkr commented on governance/polls/MIP9 Community Greenlight Poll - TUSD (TrueUSD) - January 10, 2022.md
> +# Poll: Community Greenlight Poll - TUSD (TrueUSD) - January 10, 2022
Can we make it clear that the application is for a PSM - see the forum thread

2022-01-06 13:54 UTC, mkrorbrkr commented on governance/polls/MIP9 Community Greenlight Poll - TUSD (TrueUSD) - January 10, 2022.md
> +This poll asks whether the asset TUSD (TrueUSD) should be prioritized for inclusion in the Maker Protocol by the [Core Units](https://mips.makerdao.com/mips/details/MIP38#mip38c2-core-unit-state).
Can we make it clear that the application is for a PSM - see the forum thread

2022-01-06 15:23 UTC, mkrorbrkr commented on governance/polls/MIP9 Community Greenlight Poll - TUSD-PSM (TrueUSD) - January 10, 2022.md
> +This poll asks whether applying a PSM using TUSD as collateral should be prioritized for inclusion in the Maker Protocol by the [Core Units](https://mips.makerdao.com/mips/details/MIP38#mip38c2-core-
Could you change "applying to adding" and then I think it's good to go after that

2022-01-06 15:30 UTC, mkrorbrkr approved these changes
All looks good to me @prose11

2022-01-10 14:21 UTC, prose11 approved these changes
Nice work :)

2022-01-10 14:21 UTC, merged