GL Polls [OGN] + [OUSD]
makerdao/community pull request #1618
Opened 2022-01-06 17:00 UTC by Gala-G

### Attention (CC)

## Summary of changes

_Description of the changes included in this pull request. 
Steps to follow to confirm the feature is completed or the bug/issue is resolved. 
Are there any dependencies? 
Does this code break any existing functionality or introduce any risk?_

## Relevant Context

- Feature: [ticket number](link to project management ticket)
- Relevant Pull Request: # 

## How Has This Been Tested?

## Screenshots (if appropriate):

## Further comments

--- 
## Types of changes

- [ ] Content edit, File upload, content addition
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Technical Documentation Update
- [ ] Other (please describe):

## Does this introduce a breaking change?

_Breaking change is defined as_ **"A fix or feature that would cause existing functionality to change."**

- [ ] Yes
- [ ] No

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added/changed necessary documentation (if appropriate)
- [ ] All new and existing tests passed.

2022-01-06 21:06 UTC, mkrorbrkr requested changes
Hi Gala, seems to be the same thing repeated multiple times rather than multiple issues, which is a good thing! Hopefully won't take long to fix.

The file names both need update too but I can't comment on that

2022-01-06 21:06 UTC, mkrorbrkr commented on governance/polls/ MIP9 Community Greenlight Poll - [OUSD] - January 10, 2022.md
> +title: Community Greenlight Poll - [OUSD] - January 10, 2022
Template is "$asset_code ($asset_name)". Remember, everything with a $ sign is something you need to change. So this should be "Community Greenlight Poll - OUSD (Origin Dollar) - January 10, 2022", same in the file name

2022-01-06 21:06 UTC, mkrorbrkr commented on governance/polls/ MIP9 Community Greenlight Poll - [OUSD] - January 10, 2022.md
> +summary: Signal your support or opposition to prioritising onboarding [OGN / OUSD].
$asset_code ($asset_name)

2022-01-06 21:06 UTC, mkrorbrkr commented on governance/polls/ MIP9 Community Greenlight Poll - [OUSD] - January 10, 2022.md
> +# Poll: Community Greenlight Poll - [OUSD] - January 10, 2022
$asset_code ($asset_name)

2022-01-06 21:06 UTC, mkrorbrkr commented on governance/polls/ MIP9 Community Greenlight Poll - [OUSD] - January 10, 2022.md
> +This poll asks whether the asset [OUSD] should be prioritized for inclusion in the Maker Protocol by the [Core Units](https://mips.makerdao.com/mips/details/MIP38#mip38c2-core-unit-state).
$asset_code ($asset_name)

2022-01-06 21:06 UTC, mkrorbrkr commented on governance/polls/ MIP9 Community Greenlight Poll - [OUSD] - January 10, 2022.md
> +* The 'greenlight score' will be calculated for [OUSD] using the formula `Score = 'Yes' Votes - 'No' Votes`
$asset_code ($asset_name)

2022-01-06 21:06 UTC, mkrorbrkr commented on governance/polls/ MIP9 Community Greenlight Poll - [OUSD] - January 10, 2022.md
> +* The 'greenlight score' for [OUSD] will be added to the [Collateral Prioritisation Sheet](https://docs.google.com/spreadsheets/d/1IX9e2fyfz7djtDMKn5gMyGsyFxHoY75GncMbAjnSXrM/edit#gid=0) by the Gover
$asset_code ($asset_name)

2022-01-06 21:06 UTC, mkrorbrkr commented on governance/polls/ MIP9 Community Greenlight Poll - [OUSD] - January 10, 2022.md
> +Please review the collateral onboarding application [[OUSD] MIP6 Collateral Onboarding Application - Origin Protocol & Origin Dollar](https://forum.makerdao.com/t/12205) to inform your position befor
You just need "thread" in the square brackets here, not the thread title

2022-01-07 10:56 UTC, mkrorbrkr commented
Looking good @Gala-G, just need to change the file names and then I think we're good to go!

2022-01-07 16:02 UTC, mkrorbrkr approved these changes
LGTM! @prose11

2022-01-10 14:19 UTC, prose11 approved these changes
Nice work!

2022-01-10 14:20 UTC, merged