Polls - 05232022
makerdao/community pull request #1767
Opened 2022-05-18 21:54 UTC by Gala-G

Patrick helped me out with some questions I had. It should be purrrfect :)

2022-05-19 04:41 UTC, TheExistence commented on governance/polls/Launch Maker Teleport with 1 basis point fee - May 23, 2022.md
> +The community can vote in this poll to express support or opposition to the following changes:
Please put "following change" instead of changes

2022-05-19 04:41 UTC, TheExistence commented on governance/polls/Launch Maker Teleport with 1 basis point fee - May 23, 2022.md
> +* If the Friday executive passes, then this change will become active in the Maker Protocol after the [GSM Pause Delay](https://community-development.makerdao.com/en/learn/governance/param-gsm-pause-
Please change the GSM link to: https://manual.makerdao.com/parameter-index/core/param-gsm-pause-delay
Please also change "If the Friday executive passes" to "If the executive passes". Execs aren't on Fridays anymore. The template is outdated

2022-05-20 11:25 UTC, patrick-j-govalpha requested changes
Good work. Just one small suggested change 👍

2022-05-20 11:25 UTC, patrick-j-govalpha commented on governance/polls/Launch Maker Teleport with 1 basis point fee - May 23, 2022.md
> +* Launch Maker Teleport with 1 basis point fee (0,01%)
```suggestion
* Launch Maker Teleport with a fee of 1 basis point (0.01%)
```

2022-05-20 15:59 UTC, patrick-j-govalpha approved these changes
LGTM @prose11. Thanks @Gala-G

2022-05-23 11:34 UTC, merged