Ratification polls
makerdao/community pull request #1807
Opened 2022-06-09 18:12 UTC by astronautthis

@blimpa 

MIP portal link doesn't work for MIP41c4-SP35. I've added a dummy link anyway so it should hopefully be working when you review this

2022-06-12 22:09 UTC, blimpa commented on governance/polls/Ratification Poll for Facilitator Onboarding to DIN-001 - @tadeo (MIP41c4-SP35) - June 13, 2022.md
> +* [Canonical Proposal Version](https://github.com/makerdao/mips/blob/38b7071c8668f2eb20dc35978c59183c924827ac/MIP41/MIP41c4-Subproposals/MIP41c4-SP35.md)
Use this URL: https://github.com/makerdao/mips/blob/938fcf82d93b708efe850d4e3fa942e3b8440fbc/MIP41/MIP41c4-Subproposals/MIP41c4-SP35.md

2022-06-12 22:21 UTC, blimpa commented on governance/polls/Ratification Poll for Facilitator Onboarding to DIN-001 - @tadeo (MIP41c4-SP35) - June 13, 2022.md
> +* [Latest Proposal Version](https://mips.makerdao.com/mips/details/MIP41c4SP35)
It works now :)

2022-06-12 22:21 UTC, blimpa requested changes
Left some somments :) Not sure what MIP4c3-SP1 is doing here

2022-06-13 15:05 UTC, prose11 approved these changes
Merging this through, will delete extra file later

2022-06-13 15:05 UTC, merged

2022-06-14 08:48 UTC, astronautthis commented
Thanks, sorry that extra file was from an older commit that didn't get merged.