Exec copy 2022-08-31
makerdao/community pull request #1927
Opened 2022-08-26 18:50 UTC by blimpa

Includes drawdown of 25 million DAI for HVBank and Teleport launch on Optimism and Arbitrum

@prose11

2022-08-29 16:39 UTC, patrick-j-govalpha requested changes

2022-08-29 16:39 UTC, patrick-j-govalpha commented on governance/votes/Executive vote - August 31, 2022.md
> +As per this successful governance [poll](https://vote.makerdao.com/polling/QmahjYA2#poll-detail), [Maker Teleport (formerly known as Maker Wormhole)](https://forum.makerdao.com/t/introducing-maker-wo
Debt ceiling? 1 million for each right?

2022-08-29 16:39 UTC, patrick-j-govalpha commented on governance/votes/Executive vote - August 31, 2022.md
> +As per this successful governance [poll](https://vote.makerdao.com/polling/QmQMDasC#vote-breakdown), 25 million DAI will be drawn down in the RWA-009 (HVBank) vault, if this executive proposal passes
Maybe add the following?

```suggestion
As per this successful governance [poll](https://vote.makerdao.com/polling/QmQMDasC#vote-breakdown), 25 million DAI will be drawn down in the RWA-009 (HVBank) vault, if this executive proposal passes. This is the fourth and final planned drawdown for this vault.
```

2022-08-29 16:39 UTC, patrick-j-govalpha commented on governance/votes/Executive vote - August 31, 2022.md
> +- Maker Teleport will be launched on Optimism and Arbitrum with a 1 basis point fee.
Debt ceiling?

2022-08-29 16:39 UTC, patrick-j-govalpha commented on governance/votes/Executive vote - August 31, 2022.md
> +summary: Includes drawdown of 25 million DAI for HVBank and Teleport launch on Optimism and Arbitrum.
Gotta keep the branding 😜 

```suggestion
summary: Includes drawdown of 25 million DAI for HVBank and Maker Teleport launch on Optimism and Arbitrum.
```

2022-08-29 16:39 UTC, patrick-j-govalpha commented on governance/votes/Executive vote - August 31, 2022.md
> +The Maker Teleport initiative will be bringing canonical DAI capability onto L2 domains.
```suggestion
The Maker Teleport initiative will bring canonical DAI capability onto L2 domains.
```

2022-08-29 16:39 UTC, patrick-j-govalpha commented on governance/votes/Executive vote - August 31, 2022.md
> +For more details, please read the [Signal Request from which the passed governance poll spawned off](https://forum.makerdao.com/t/signal-request-launch-maker-teleport-with-1-basis-point-fee/15109) an
Wording is a bit clunky IMO. Maybe change to:

```suggestion
For more details, please review the original [Signal Request](https://forum.makerdao.com/t/signal-request-launch-maker-teleport-with-1-basis-point-fee/15109) that led to the governance poll, and the [Maker Teleport: Oracle Launch Configuration post](https://forum.makerdao.com/t/maker-teleport-oracle-launch-configuration/17471). Forum threads related to the Teleport initiative can be found [here](https://forum.makerdao.com/tag/teleport).
```

2022-08-30 14:24 UTC, prose11 approved these changes
Nice work everyone :)

2022-08-30 14:25 UTC, merged