Create Executive vote - October 19, 2022.md
makerdao/community pull request #1993
Opened 2022-10-13 19:47 UTC by patrick-j-govalpha

Adds 2022-10-19 exec copy

2022-10-13 20:24 UTC, blimpa requested changes
LGTM

2022-10-13 20:24 UTC, blimpa commented on governance/votes/Executive vote - October 19, 2022.md
> +As per this successful governance [poll](https://vote.makerdao.com/polling/QmYffkvR#vote-breakdown) the following parameter changes will be made to the GUSD PSM (PSM-GUSD-A) if this executive proposa
```suggestion
As per this successful governance [poll](https://vote.makerdao.com/polling/QmYffkvR#vote-breakdown), the following parameter changes will be made to the GUSD PSM (PSM-GUSD-A) if this executive proposal passes:
```

2022-10-13 20:24 UTC, blimpa commented on governance/votes/Executive vote - October 19, 2022.md
> +- A Debt Ceiling Instant Access Module with the parameters listed below will be added to the RWA-007-A Vault.
```suggestion
- A Debt Ceiling Instant Access Module (DC-IAM) with the parameters listed below will be added to the RWA-007-A Vault.
```

2022-10-13 20:25 UTC, blimpa commented on governance/votes/Executive vote - October 19, 2022.md
> +summary: Enables the Debt Ceiling Instant Access Module for RWA-007-A, parameter changes for the GUSD PSM.
```suggestion
summary: Enabling the Debt Ceiling Instant Access Module for RWA-007-A, parameter changes for the GUSD PSM.
```

2022-10-13 20:26 UTC, blimpa commented on governance/votes/Executive vote - October 19, 2022.md
> +summary: Enables the Debt Ceiling Instant Access Module for RWA-007-A, parameter changes for the GUSD PSM.
For consistency ¯\_(ツ)_/¯

2022-10-13 20:44 UTC, patrick-j-govalpha commented on governance/votes/Executive vote - October 19, 2022.md
> +summary: Enables the Debt Ceiling Instant Access Module for RWA-007-A, parameter changes for the GUSD PSM.
fixed in 76e6867d23308ab4fc31190b816f5acaa73b60f4

2022-10-14 17:20 UTC, patrick-j-govalpha commented on governance/votes/Executive vote - October 19, 2022.md
> +- A Debt Ceiling Instant Access Module (DC-IAM) with the parameters listed below will be added to the RWA-007-A Vault.
We tend to prefer "Human-readable" language for exec copy wherever possible. I can change it to Vault type though which is probably more accurate.

2022-10-14 19:30 UTC, merged