Executive Vote - December 9, 2022
makerdao/community pull request #2056
Opened 2022-12-01 22:46 UTC by astronautthis

2022-12-02 12:14 UTC, patrick-j-govalpha requested changes
Initial review - waiting for final Blocktower details so still need to review those sections

2022-12-02 12:14 UTC, patrick-j-govalpha commented on governance/votes/Executive Vote - December 9, 2022.md
> +##### [Fee In (`tin`)](https://manual.makerdao.com/module-index/module-psm#fee-in-tin) Increases
Move PSM line change to PSM section (this was my error in the original poll!
```suggestion

##### [Target Available Debt (`gap`)](https://manual.makerdao.com/module-index/module-dciam#target-available-debt-gap) Reductions
- Reduce the WSTETH-A Target Available Debt (`gap`) by 15 million DAI from 30 million DAI to **15 million DAI**.
- Reduce the WSTETH-B Target Available Debt (`gap`) by 15 million DAI from 30 million DAI to **15 million DAI**.
- Reduce the WBTC-A Target Available Debt (`gap`) by 60 million DAI from 80 million DAI to **20 million DAI**.
- Reduce the WBTC-B Target Available Debt (`gap`) by 20 million DAI from 30 million DAI to **10 million DAI**.
- Reduce the WBTC-C Target Available Debt (`gap`) by 80 million DAI from 100 million DAI to **20 million DAI**.
- Reduce the LINK-A Target Available Debt (`gap`) by 4.5 million DAI from 7 million DAI to **2.5 million DAI**.
- Reduce the YFI-A Target Available Debt (`gap`) by 5.5 million DAI from 7 million DAI to **1.5 million DAI**.

##### [Ceiling Increase Cooldown (`ttl`)](https://manual.makerdao.com/module-index/module-dciam#ceiling-increase-cooldown-ttl) Increases
- Increase the WBTC-A Ceiling Increase Cooldown (`ttl`) by 18 hours from 6 hours to **24 hours**.
- Increase the WBTC-B Ceiling Increase Cooldown (`ttl`) by 16 hours from 8 hours to **24 hours**.
- Increase the WBTC-C Ceiling Increase Cooldown (`ttl`) by 16 hours from 8 hours to **24 hours**.

#### [Peg Stability Module (PSM)](https://manual.makerdao.com/module-index/module-psm) Parameter Changes

##### [Maximum Debt Ceiling (`line`)](https://manual.makerdao.com/module-index/module-dciam#maximum-debt-ceiling-line) Reduction
- Reduce the PSM-USDP-A Maximum Debt Ceiling (`line`) by 50 million DAI from 500 million DAI to **450 million DAI**.

##### [Fee In (`tin`)](https://manual.makerdao.com/module-index/module-psm#fee-in-tin) Increases
```

2022-12-02 12:14 UTC, patrick-j-govalpha commented on governance/votes/Executive Vote - December 9, 2022.md
> +## Review
Add DSR MOM link

```suggestion
Please review the [discussion thread](https://forum.makerdao.com/t/parameter-changes-proposal-ppg-omc-001-24-november-2022/18925#dai-savings-rate-adjustment-3) containing information about the DAI Savings Rate Adjustment to inform your position before voting.

For more information on the DAI Savings Rate please refer to the documentation [here](https://manual.makerdao.com/parameter-index/core/param-dai-savings-rate).

## Review
```

2022-12-06 13:04 UTC, patrick-j-govalpha commented
@prose11 would appreciate your set of eyes on this too

2022-12-07 12:38 UTC, patrick-j-govalpha requested changes

2022-12-07 17:19 UTC, miguel567 commented on governance/votes/Executive Vote - December 9, 2022.md
> +* **RWA011_A_JAR:** ``.
Centrifuge vaults don't have Jar contracts. You can remove this line totally.

2022-12-08 11:25 UTC, patrick-j-govalpha approved these changes
Thanks everyone, huge copy this week, spare a thought for the poor devs

2022-12-08 11:30 UTC, merged