Polls - 2023-05-08
makerdao/community pull request #2223
Opened 2023-05-04 14:06 UTC by LongForWisdom

2023-05-04 15:06 UTC, blimpa requested changes

2023-05-04 15:06 UTC, blimpa commented on governance/polls/Ratification Poll for MIP Amendment Subproposals - MIP102c2-SP7 - May 08, 2023.md
> +* The Arbitration Facilitators will confirm its passage by marking the proposal **Accepted** on the [MIPs portal](https://mips.makerdao.com/mips/list) and across all other relevant governance mediums
```suggestion
* The Arbitration Facilitators will confirm its passage by marking the proposal **Accepted** on the [MIPs portal](https://mips.makerdao.com/mips/list) and across all other relevant governance mediums. 
* The amendment pull request will be merged into the MIP repository.
```

2023-05-04 15:06 UTC, blimpa commented on governance/polls/Ratification Poll for MIP Amendment Subproposals - MIP102c2-SP7 - May 08, 2023.md
> +* Any further work required to implement the proposal will be tasked to the relevant [Core Units](https://mips.makerdao.com/mips/details/MIP38#mip38c2-core-unit-state).
Remove?

2023-05-04 15:06 UTC, blimpa commented on governance/polls/Ratification Poll for MIP Amendment Subproposals - MIP102c2-SP7 - May 08, 2023.md
> +title: Ratification Poll for MIP Amendment Subproposals (MIP102c2-SP7) - May 08, 2023
```suggestion
title: Ratification Poll for MIP Amendment Subproposals (MIP102c2-SP7) - May 8, 2023
```

2023-05-04 15:06 UTC, blimpa commented on governance/polls/Ratification Poll for MIP Amendment Subproposals - MIP102c2-SP7 - May 08, 2023.md
> +# Ratification Poll for MIP Amendment Subproposals (MIP102c2-SP7) - May 08, 2023
```suggestion
# Ratification Poll for MIP Amendment Subproposals (MIP102c2-SP7) - May 8, 2023
```

2023-05-04 15:06 UTC, blimpa commented on governance/polls/Ratification Poll for MIP Amendment Subproposals - MIP102c2-SP7 - May 08, 2023.md
> +The Arbitration Facilitators have placed a ratification poll into the [voting system](https://vote.makerdao.com/polling) as part of the responsibilities defined in [MIP51](https://mips.makerdao.com/m
```suggestion
The Arbitration Facilitators have placed a ratification poll into the [voting system](https://vote.makerdao.com/polling) as part of the responsibilities defined in [MIP51](https://mips.makerdao.com/mips/details/MIP51). This Governance [Poll](https://manual.makerdao.com/governance/governance-cycle/weekly-governance-cycle#weekly-governance-cycle-definitions-mip16c1) will be active for fourteen days beginning on Monday, May 8 at 16:00 UTC.
```

2023-05-04 15:06 UTC, blimpa commented on governance/polls/Ratification Poll for MIP Amendment Subproposals - MIP102c2-SP7 - May 08, 2023.md
> +* [Canonical Proposal Version](https://github.com/makerdao/mips/blob/e22e5ed2be970e1b285553028db7eed123531803/MIP102/MIP102c2-Subproposals/MIP102c2-SP7.md)
```suggestion
* [Canonical Proposal Version](https://github.com/makerdao/mips/blob/5d37617bd4b3cd7cbd714308ff91bdb5564d3002/MIP102/MIP102c2-Subproposals/MIP102c2-SP7.md)
```

2023-05-05 12:10 UTC, LongForWisdom commented
Appreciate the comments, @blimpa !

2023-05-05 12:38 UTC, LongForWisdom commented on governance/polls/Amend Keeper Networks - May 8, 2023.md
> +
Needs finishing, and addresses chasing down.

2023-05-08 14:24 UTC, merged