RPs to go on-chain on 2023-06-12
makerdao/community pull request #2301
Opened 2023-06-06 21:37 UTC by blimpa

- MIP102c2-SP8
- MIP102c2-SP9

2023-06-08 14:58 UTC, LongForWisdom requested changes

2023-06-08 14:58 UTC, LongForWisdom commented on governance/polls/Ratification Poll - MIP Amendment Subproposal (MIP102c2-SP8) - June 12, 2023.md
> +The Arbitration Facilitators have placed a ratification poll into the [voting system](https://vote.makerdao.com/polling) as part of the responsibilities defined in [MIP51](https://mips.makerdao.com/m
```suggestion
The Governance Facilitator has placed a ratification poll into the [voting system](https://vote.makerdao.com/polling) as part of the responsibilities defined in [MIP51](https://mips.makerdao.com/mips/details/MIP51). This Governance [Poll](https://manual.makerdao.com/governance/governance-cycle/weekly-governance-cycle#weekly-governance-cycle-definitions-mip16c1) will be active for fourteen days beginning on Monday, June 12 at 16:00 UTC.
```

2023-06-08 14:58 UTC, LongForWisdom commented on governance/polls/Ratification Poll - MIP Amendment Subproposal (MIP102c2-SP8) - June 12, 2023.md
> +* Any further work required to implement the proposal will be tasked to the relevant [Ecosystem Actors](https://mips.makerdao.com/mips/details/MIP101#7-professional-actors).
The subheading link here doesn't go anywhere. Should be updated.

2023-06-08 14:58 UTC, LongForWisdom commented on governance/polls/Ratification Poll - MIP Amendment Subproposal (MIP102c2-SP8) - June 12, 2023.md
> +* [Canonical Proposal Version](TBD)
Missing link. Pretty sure you know, but just to make sure it isn't missed.

2023-06-08 14:58 UTC, LongForWisdom commented on governance/polls/Ratification Poll - MIP Amendment Subproposal (MIP102c2-SP8) - June 12, 2023.md
> +* [Amendment Pull Request](TBD)
Missing link. Pretty sure you know, but just to make sure it isn't missed.

2023-06-08 14:58 UTC, LongForWisdom commented on governance/polls/Ratification Poll - MIP Amendment Subproposal (MIP102c2-SP9) - June 12, 2023.md
> +summary: This subproposal incorporates the Bug Bounty Programa (originally MIP64) into MIP107.
```suggestion
summary: This subproposal incorporates the Bug Bounty Program (originally MIP64) into MIP107.
```

2023-06-08 14:58 UTC, LongForWisdom commented on governance/polls/Ratification Poll - MIP Amendment Subproposal (MIP102c2-SP8) - June 12, 2023.md
> +The Arbitration Facilitators have placed a ratification poll into the [voting system](https://vote.makerdao.com/polling) as part of the responsibilities defined in [MIP51](https://mips.makerdao.com/m
Should the last link here go to the monthly governance cycle page rather than the weekly?

2023-06-08 14:58 UTC, LongForWisdom commented on governance/polls/Ratification Poll - MIP Amendment Subproposal (MIP102c2-SP9) - June 12, 2023.md
> +The Arbitration Facilitators have placed a ratification poll into the [voting system](https://vote.makerdao.com/polling) as part of the responsibilities defined in [MIP51](https://mips.makerdao.com/m
```suggestion
The Governance Facilitator has placed a ratification poll into the [voting system](https://vote.makerdao.com/polling) as part of the responsibilities defined in [MIP51](https://mips.makerdao.com/mips/details/MIP51). This Governance [Poll](https://manual.makerdao.com/governance/governance-cycle/weekly-governance-cycle#weekly-governance-cycle-definitions-mip16c1) will be active for fourteen days beginning on Monday, June 12 at 16:00 UTC.
```

2023-06-08 14:58 UTC, LongForWisdom commented on governance/polls/Ratification Poll - MIP Amendment Subproposal (MIP102c2-SP9) - June 12, 2023.md
> +The Arbitration Facilitators have placed a ratification poll into the [voting system](https://vote.makerdao.com/polling) as part of the responsibilities defined in [MIP51](https://mips.makerdao.com/m
Should the last link here go to the monthly governance cycle page rather than the weekly?

2023-06-08 14:58 UTC, LongForWisdom commented on governance/polls/Ratification Poll - MIP Amendment Subproposal (MIP102c2-SP9) - June 12, 2023.md
> +* The Arbitration Facilitators will confirm its passage by marking the proposal **Accepted** on the [MIPs portal](https://mips.makerdao.com/mips/list) and across all other relevant governance mediums
```suggestion
* The Governance Facilitator will confirm its passage by marking the proposal **Accepted** on the [MIPs portal](https://mips.makerdao.com/mips/list) and across all other relevant governance mediums.
```

2023-06-08 14:58 UTC, LongForWisdom commented on governance/polls/Ratification Poll - MIP Amendment Subproposal (MIP102c2-SP9) - June 12, 2023.md
> +* Any further work required to implement the proposal will be tasked to the relevant [Ecosystem Actors](https://mips.makerdao.com/mips/details/MIP101#7-professional-actors).
Link is semi-dead

2023-06-12 10:58 UTC, patrick-j-govalpha approved these changes
Looking good, thanks!

2023-06-12 10:59 UTC, merged