2024-03-06 Spell copy
makerdao/community pull request #2580
Opened 2024-03-04 11:13 UTC by 0xldr

Spark proxy spell address is pending - labelled `$TBD` in text.

2024-03-04 14:06 UTC, MakerJanSky requested changes
Nice job, ldr.

2024-03-04 15:27 UTC, VoteWizard requested changes

2024-03-04 15:27 UTC, VoteWizard commented on governance/votes/Executive Vote - March 6, 2024.md
> +title: Template - [Executive Vote] Executive Vote - March 6, 2024
We typically include the items contained in the spell in the title for better searchability and consistency. Is there a reason for excluding them this time?

2024-03-04 15:27 UTC, VoteWizard commented on governance/votes/Executive Vote - March 6, 2024.md
> +# [Executive Proposal] Executive Vote - March 6, 2024
Same issue with the title described above

2024-03-04 17:47 UTC, merged

2024-03-05 18:19 UTC, blimpa commented on governance/votes/Executive Vote - March 6, 2024.md
> +- Twelve Aligned Delegates will receive a total of 259.83 MKR as compensation for February 2024.
Are we no longer using "as detailed below"?

2024-03-05 18:19 UTC, blimpa commented on governance/votes/Executive Vote - March 6, 2024.md
> +### WBTC Vault [Target Available Debt `gap`](https://mips.makerdao.com/mips/details/MIP104#14-3-1-4-2-target-available-debt-gap-) Changes
"(`gap`)"

2024-03-05 18:19 UTC, blimpa commented on governance/votes/Executive Vote - March 6, 2024.md
> +**WETH**
(It's more semantically appropriate to make these headers, I think)