Polls 20240527
makerdao/community pull request #2652
Opened 2024-05-26 12:37 UTC by CivicSage3

version reworked after @blimpa 's comments (thanks)

2024-05-26 12:38 UTC, CivicSage3 commented
@VoteWizard @blimpa 
version after blimpa's comments

2024-05-27 04:52 UTC, VoteWizard commented on governance/polls/SparkLend Ethereum - Increase Morpho DAI Vault Supply Caps - May 27, 2024.md
> +The Governance Facilitators have placed a Governance Poll into the voting system on behalf of Spark Protocol and the Stability Scope Facilitators. This Governance [Poll](https://manual.makerdao.com/g
```suggestion
The Governance Facilitators have placed a Governance Poll into the voting system on behalf of Spark Protocol and the Stability Facilitators. This Governance [Poll](https://manual.makerdao.com/governance/governance-cycle/weekly-governance-cycle#weekly-governance-cycle-definitions-mip16c1) will be active for three days beginning on Monday, May 27 at 16:00 UTC.
```
I'm removing "Scope" as it is only used in the term Stability Scope Facilitator and not in Governance Facilitators, to keep the document consistent

2024-05-27 07:07 UTC, VoteWizard reviewed
Good job @CivicSage3 and @blimpa. I left a few comments

2024-05-27 07:07 UTC, VoteWizard commented on governance/polls/SparkLend Gnosis - Turn Off Bridge Security Delay  - May 27, 2024.md.md
> +- Lowering the security delay for SparkLend governance on Gnosis from 2 days to **0 days**.
```suggestion
- Lower the security delay for SparkLend governance on Gnosis from 2 days to **0 days**.
```

2024-05-27 07:07 UTC, VoteWizard commented on governance/polls/SparkLend Gnosis - Turn Off Bridge Security Delay  - May 27, 2024.md.md
> +- Setting the minimum security delay limit to **0**.
```suggestion
- Set the minimum security delay limit to **0**.
```

2024-05-27 07:07 UTC, VoteWizard commented on governance/polls/SparkLend Gnosis - Turn Off Bridge Security Delay  - May 27, 2024.md.md
> +- Setting the minimum security delay limit to **0**.
Good

2024-05-27 07:07 UTC, VoteWizard commented on governance/polls/SparkLend Gnosis - Turn Off Bridge Security Delay  - May 27, 2024.md.md
> +[BA Labs ](https://forum.makerdao.com/t/may-21-2024-proposed-changes-to-sparklend-for-upcoming-spell/24327/2) confirm that removing the delay will not impact the risk profile of the Gnosis market.
```suggestion
[BA Labs](https://forum.makerdao.com/t/may-21-2024-proposed-changes-to-sparklend-for-upcoming-spell/24327/2) confirms that removing the delay will not impact the risk profile of the Gnosis market.
```

2024-05-27 13:08 UTC, 0xldr requested changes

2024-05-27 13:08 UTC, 0xldr commented on governance/polls/SparkLend Ethereum and Gnosis - Turn off Siloed Borrowing for USDC, USDT, and EURe - May 27, 2024.md
> +title: SparkLend Ethereum and Gnosis - Turn off Siloed Borrowing for USDC, USDT and EURe - May 27, 2024
Add Oxford comma to match the file name

```suggestion
title: SparkLend Ethereum and Gnosis - Turn off Siloed Borrowing for USDC, USDT, and EURe - May 27, 2024
```

2024-05-27 13:08 UTC, 0xldr commented on governance/polls/SparkLend Ethereum and Gnosis - Turn off Siloed Borrowing for USDC, USDT, and EURe - May 27, 2024.md
> +# Poll: SparkLend Ethereum and Gnosis - Turn off Siloed Borrowing for USDC, USDT and EURe - May 27, 2024
Add Oxford comma to match the file name

```suggestion
# Poll: SparkLend Ethereum and Gnosis - Turn off Siloed Borrowing for USDC, USDT, and EURe - May 27, 2024
```

2024-05-27 13:08 UTC, 0xldr commented on governance/polls/SparkLend Ethereum and Gnosis - Turn off Siloed Borrowing for USDC, USDT, and EURe - May 27, 2024.md
> +title: SparkLend Ethereum and Gnosis - Turn off Siloed Borrowing for USDC, USDT and EURe - May 27, 2024
or rename the file

2024-05-27 13:08 UTC, 0xldr commented on governance/polls/SparkLend Ethereum and Gnosis - Update Interest Rate Models for ETH, DAI, USDC, USDT, and EURe - May 27, 2024.md
> +        - Increase optimal utilization from 90% to 95%
add deltas where parameters are changing

2024-05-27 13:08 UTC, 0xldr commented on governance/polls/SparkLend Ethereum and Gnosis - Update Interest Rate Models for ETH, DAI, USDC, USDT, and EURe - May 27, 2024.md
> +        - Increase optimal utilization from 90% to 95%
Also consider use of subheadings to separate chains and coins

e.g.

```
## Review

### Ethereum

#### ETH
```

2024-05-27 13:08 UTC, 0xldr commented on governance/polls/SparkLend Gnosis - Turn Off Bridge Security Delay  - May 27, 2024.md
> +- Lower the security delay for SparkLend governance on Gnosis from 2 days to **0 days**.
clarify that it is the bridge security delay and add the delta

```suggestion
- Lower the bridge security delay for SparkLend governance on Gnosis by 2 days from 2 days to **0 days**.
```

2024-05-27 13:08 UTC, 0xldr commented on governance/polls/SparkLend Gnosis - Turn Off Bridge Security Delay  - May 27, 2024.md
> +- Phoenix Labs will prepare a Spark spell to lower the security delay for Spark governance to 0 days and to set the minimum security delay limit to 0 on Gnosis.
```suggestion
- Phoenix Labs will prepare a Spark spell to lower the bridge security delay for Spark governance to 0 days and to set the minimum security delay limit to 0 on Gnosis.
```

2024-05-27 15:24 UTC, merged

2024-05-27 15:25 UTC, 0xldr approved these changes