Create Risk Premium Adjustment for ETH-A Vault.md
makerdao/community pull request #795
Opened 2020-09-17 21:17 UTC by ahbartsch

@LongForWisdom

2020-09-17 22:29 UTC, LongForWisdom requested changes
Mostly great. See comments for suggested minor changes. Thanks Aaron.

2020-09-17 22:29 UTC, LongForWisdom commented on governance/polls/Risk Premium Adjustment for ETH-A Vault.md
> +---
Filename should match title: Adjust the ETH-A Risk Premium - September 21, 2020.md

2020-09-17 22:29 UTC, LongForWisdom commented on governance/polls/Risk Premium Adjustment for ETH-A Vault.md
> +summary: Signal your support for increasing the ETH-A Risk Premium to from 0% to 2%
support or opposition

2020-09-17 22:29 UTC, LongForWisdom commented on governance/polls/Risk Premium Adjustment for ETH-A Vault.md
> +The ETH-A Risk Premium was voted on in a forum signal request. Please review the [Thread](https://forum.makerdao.com/t/signal-request-increase-eth-a-risk-premium-september-2020/4042) to inform your p
super minor. Lowercase t for Thread.

2020-09-17 22:45 UTC, ahbartsch commented
Donezo.

2020-09-18 11:36 UTC, LongForWisdom approved these changes
Thanks Aaron!

2020-09-19 19:32 UTC, merged